@startuml User


package Content{
    class Post extends Article{
    }
    class Vote{
        upVote : boolean
        timeOfVote : Date 
        Owner : RegisteredUser
        originArticle : Article
    }
    class Project extends Article{
        description: String
        fundGoal : Double
        raisedFunding : Double
        endDate : Date
        createdDate : Date
        fundRaisers : RegisteredUser[]
    }

    class Comment extends Article{
        originArticle: Article
    }
    class Article{
        _id : String
        owner : RegisteredUser
        type : String
        content: String
        votes : Vote[]
        comments : Comment[]
        media : Media[]
    }
    class Media{
        _id : String
        name : String


    }
    class Image extends Media{
        hash : String
        sha256 : String
        ext : String
        mime : String
        size : 0
        url : String
        provider : String
        provider_metadata : {}
        related : String

    }
    class Video extends Media{
        url: String
        title : String
        platform : String
    }
    Article o-* Vote
    Article *-right-* Comment
    Project o-left- Post
    Article o-- Media

}
package Messanging {

    class MessageBox{
        String _id
        Conversation[] conversations
        RegisteredUser owner
    }
    class Conversation{
        String _id
        Message[] messages
        RegisteredUser[] participants
    }
    class Message{
        String _id
        Date sentTime
        Date receivedTime
        RegisteredUser owner
    }


}

package User{

    class User {
        addressIp : String
        previousSession: Session
        currentSession: Session
    }

    class Session{
        _id: String
        addressIp: String
        visitingTime: Date
        leavingTime: Date
    }

    class RegisteredUser extends User{
        _id : String
        aboutMe : String
        address : Location
        projects : Project[]
        following : RegisteredUser[]
        followers : RegisteredUser[]
        socialMedia : ContactMe[]
        posts : Post[]
        messageBox : MessageBox
        fundedProjects : Project[]

    }
    class Visitor extends User{
    }
    class Location{
        country : Country
        state : State
        city : City
        line1 : String
        line2 : String
        zipCode : String
        longitude : Double
        latitude : Double
    }
    class SocialMedia{
        type: String
        tag: String
    }
}



MessageBox  *--*  RegisteredUser

Article  *--*  RegisteredUser

RegisteredUser *--* Location
Vote  *---*  RegisteredUser

MessageBox  *-down-*  Conversation
Message  *-up-*  Conversation


@enduml
