@startuml User


package Content{
    class Post extends Article{
        _id : String
        Owner : RegisteredUser
        content String
        comments Comment[]
        votes Vote[]
    }
    class Vote{
        boolean upVote
        Date timeOfVote
        RegisteredUser Owner
        Article originArticle
    }
    class Project extends Article{
        String _id
        String description
        Double fundGoal
        Double raisedFunding
        Date endDate
        RegisteredUser[] backers
    }

    class Comment extends Article{
        String _id
        RegisteredUser Owner
        String content
        Article originArticle
    }
    class Article{
        _id : String
        owner : RegisteredUser
        type : String
        votes : Vote[]
        comments : Comment[]
        medias : Media[]
    }
    class Media{
        _id : String
        name : String
        hash : String
        sha256 : String
        ext : String
        mime : String
        size : 0
        url : String
        provider : String
        provider_metadata : {}
        related : String


    }
    class Image extends Media{

    }
    class Video extends Media{

    }
    Article o-* Vote
    Article *-right-* Comment
    Project o-left- Post
    Article o-- Media

}
package Messanging {

    class MessageBox{
        String _id
        Conversation[] conversations
        RegisteredUser owner
    }
    class Conversation{
        String _id
        Message[] messages
        RegisteredUser[] participants
    }
    class Message{
        String _id
        Date sentTime
        Date receivedTime
        RegisteredUser owner
    }


}

package User{

    class User {
        addressIp : String
        visitingTime : Date
        leavingTime : Date
        sessionDuration : Time

        calculateSessionDuration() : void
    }


    class RegisteredUser extends User{
        _id : String
        aboutMe : String
        address : Location
        projects : Project[]
        following : RegisteredUser[]
        followers : RegisteredUser[]
        socialMedia : ContactMe[]
        posts : Post[]
        messageBox : MessageBox
        fundedProjects : Project[]

    }
    class Visitor extends User{
    }
    class Location{
        country : Country
        state : State
        city : City
        line1 : String
        line2 : String
        zipCode : String
        longitude : Double
        latitude : Double
    }
}



MessageBox  *--*  RegisteredUser

Article  *--*  RegisteredUser

RegisteredUser *--* Location
Vote  *---*  RegisteredUser

MessageBox  *-down-*  Conversation
Message  *-up-*  Conversation


@enduml
